import '../components/nav-bar.js'
import '../components/hiking-trails.js'
import '../components/custom-header.js'
import '../components/favourite-trails.js'
import '../components/chosen-trail.js'
import '../components/map-search.js'
import '../components/all-trails.js'